# Generated by Django 4.1.5 on 2023-01-02 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=300)),
                ("name_slug", models.CharField(max_length=300)),
                ("text", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("title_slug", models.CharField(max_length=300)),
                ("cover", models.CharField(blank=True, max_length=300, null=True)),
                (
                    "cover_source",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                ("spine_color", models.CharField(blank=True, max_length=7, null=True)),
                (
                    "goodreads_id",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("isbn10", models.CharField(blank=True, max_length=30, null=True)),
                ("isbn13", models.CharField(blank=True, max_length=30, null=True)),
                ("dimensions", models.JSONField(null=True)),
                ("source", models.CharField(blank=True, max_length=300, null=True)),
                ("pages", models.IntegerField(blank=True, null=True)),
                ("publication_year", models.IntegerField(blank=True, null=True)),
                ("date_added", models.DateField()),
                ("series", models.CharField(blank=True, max_length=300, null=True)),
                (
                    "series_position",
                    models.CharField(blank=True, max_length=5, null=True),
                ),
                ("plot", models.TextField(blank=True, null=True)),
                ("authors", models.ManyToManyField(to="main.author")),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=300)),
                ("name_slug", models.CharField(max_length=300)),
                ("text", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ToRead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("author", models.CharField(max_length=300)),
                ("shelf", models.CharField(max_length=300)),
                ("pages", models.IntegerField(blank=True, null=True)),
                ("source", models.CharField(default="calibre", max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("tldr", models.TextField(blank=True, null=True)),
                ("rating", models.IntegerField(blank=True, null=True)),
                ("did_not_finish", models.BooleanField(default=False)),
                ("latest_date", models.DateField()),
                ("dates_read", models.CharField(blank=True, max_length=300, null=True)),
                ("social", models.JSONField(null=True)),
                (
                    "book",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT, to="main.book"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Quote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("order", models.IntegerField(blank=True, null=True)),
                (
                    "source_author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quotes",
                        to="main.author",
                    ),
                ),
                (
                    "source_book",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quotes",
                        to="main.book",
                    ),
                ),
            ],
            options={
                "ordering": ("source_author", "source_book", "order", "id"),
            },
        ),
        migrations.CreateModel(
            name="BookRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                (
                    "destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="main.book",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="related_books",
                        to="main.book",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="book",
            name="book_tags",
            field=models.ManyToManyField(to="main.tag"),
        ),
    ]
