# Generated by Django 4.1.5 on 2023-01-02 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="cover",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
    ]
