# Generated by Django 4.1.5 on 2023-01-02 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_quote_language"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="book_tags",
            new_name="tags",
        ),
        migrations.AlterField(
            model_name="review",
            name="book",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="review",
                to="main.book",
            ),
        ),
    ]
