# Generated by Django 4.1.5 on 2023-01-02 22:44

from django.db import migrations


def set_primary_author(apps, schema_editor):
    Book = apps.get_model("main", "Book")
    for book in Book.objects.all().prefetch_related("additional_authors"):
        book.primary_author = book.additional_authors.first()
        book.additional_authors.clear()
        book.save()


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_rename_authors_book_additional_authors_and_more"),
    ]

    operations = [migrations.RunPython(set_primary_author, migrations.RunPython.noop)]
