# Generated by Django 4.1.5 on 2023-01-03 01:14

from django.db import migrations, models
import scriptorium.main.models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_primary_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="cover",
            field=models.ImageField(
                blank=True, null=True, upload_to=scriptorium.main.models.get_cover_path
            ),
        ),
    ]
