# Generated by Django 4.1.5 on 2023-01-03 01:22

from django.db import migrations, models
import scriptorium.main.models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_alter_book_cover"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="cover",
            field=models.ImageField(
                blank=True,
                max_length=800,
                null=True,
                upload_to=scriptorium.main.models.get_cover_path,
            ),
        ),
    ]
