# Generated by Django 4.1.5 on 2023-01-03 12:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0008_alter_book_cover"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="toread",
            unique_together={("title", "author")},
        ),
    ]
