# Generated by Django 4.1.5 on 2023-01-09 20:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0009_alter_toread_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="is_draft",
            field=models.BooleanField(default=False),
        ),
    ]
