# Generated by Django 4.1.5 on 2023-01-30 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_review_is_draft"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="openlibrary_id",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="additional_authors",
            field=models.ManyToManyField(blank=True, to="main.author"),
        ),
        migrations.AlterField(
            model_name="book",
            name="date_added",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="dimensions",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
