# Generated by Django 4.1.5 on 2023-03-14 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0011_book_openlibrary_id_alter_book_additional_authors_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("slug", models.CharField(max_length=300)),
                ("text", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
