# Generated by Django 4.1.5 on 2023-03-15 16:20

from django.db import migrations, models
import django.db.models.deletion
import scriptorium.main.models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0012_page"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="slug",
            field=models.CharField(max_length=300, unique=True),
        ),
        migrations.CreateModel(
            name="Thumbnail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("size", models.CharField(max_length=255)),
                (
                    "thumb",
                    models.FileField(
                        upload_to=scriptorium.main.models.get_thumbnail_path
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="thumbnails",
                        to="main.book",
                    ),
                ),
            ],
        ),
    ]
