# Generated by Django 4.1.9 on 2023-06-14 12:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0013_alter_page_slug_thumbnail"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tag",
            options={"ordering": ("category", "name_slug")},
        ),
        migrations.RemoveField(
            model_name="tag",
            name="name",
        ),
        migrations.AddField(
            model_name="tag",
            name="category",
            field=models.CharField(
                choices=[
                    ("genre", "genre"),
                    ("format", "format"),
                    ("language", "language"),
                    ("awards", "awards"),
                    ("themes", "themes"),
                ],
                default="genre",
                max_length=300,
            ),
        ),
    ]
