# Generated by Django 4.1.9 on 2023-06-14 12:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0013_alter_page_slug_thumbnail"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tag",
            options={"ordering": ("category", "name_slug")},
        ),
        migrations.RenameField(
            model_name="tag",
            old_name="name",
            new_name="category",
        ),
    ]
