# Generated by Django 4.1.9 on 2023-06-18 17:42

from django.db import migrations, models
import scriptorium.main.models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0014_alter_tag_options_remove_tag_name_tag_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="category",
            field=models.CharField(
                choices=[
                    ("genre", "genre"),
                    ("format", "format"),
                    ("language", "language"),
                    ("awards", "awards"),
                    ("themes", "themes"),
                    ("author", "author"),
                ],
                default="genre",
                max_length=300,
            ),
        ),
        migrations.AlterField(
            model_name="thumbnail",
            name="thumb",
            field=models.FileField(
                max_length=800, upload_to=scriptorium.main.models.get_thumbnail_path
            ),
        ),
    ]
