# Generated by Django 4.1.9 on 2023-10-20 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0015_alter_tag_category_alter_thumbnail_thumb"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quote",
            name="source_author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quotes",
                to="main.author",
            ),
        ),
        migrations.AlterField(
            model_name="quote",
            name="source_book",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quotes",
                to="main.book",
            ),
        ),
        migrations.CreateModel(
            name="Poem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "book_title",
                    models.CharField(
                        blank=True,
                        help_text="Use if neither book nor author are in the database",
                        max_length=300,
                        null=True,
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("slug", models.CharField(max_length=300)),
                ("text", models.TextField()),
                ("language", models.CharField(default="en", max_length=2)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("A", "archived"),
                            ("W", "waiting"),
                            ("L", "learning"),
                            ("M", "memorized"),
                        ],
                        default="A",
                        max_length=1,
                    ),
                ),
                ("learning_data", models.JSONField(blank=True, null=True)),
                ("date_added", models.DateField(auto_now_add=True)),
                ("last_studied", models.DateField(blank=True, null=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        help_text="Use if the book is not in the database",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="poems",
                        to="main.author",
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="poems",
                        to="main.book",
                    ),
                ),
            ],
            options={
                "unique_together": {("book", "slug")},
            },
        ),
    ]
