# Generated by Django 4.1.9 on 2023-10-20 15:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0017_remove_poem_book_title_poem_author_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="poem",
            name="context",
            field=models.TextField(blank=True, null=True),
        ),
    ]
