# Generated by Django 4.1.9 on 2024-01-17 19:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0018_poem_context"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="feed_date",
            field=models.DateField(null=True),
        ),
    ]
