# Generated by Django 4.1.13 on 2024-08-03 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0019_review_feed_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="ToReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("author", models.CharField(max_length=300)),
                ("notes", models.TextField(blank=True, null=True)),
                ("date_started", models.DateField(blank=True, null=True)),
                ("date_finished", models.DateField(blank=True, null=True)),
            ],
            options={
                "unique_together": {("title", "author")},
            },
        ),
    ]
