# Generated by Django 4.1.13 on 2024-08-18 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0021_rename_date_finished_toreview_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="toreview",
            name="series",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="toreview",
            name="series_position",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
