# Generated by Django 4.1.13 on 2024-08-18 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0022_toreview_series_toreview_series_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="toreview",
            name="quotes_file",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
    ]
