# Generated by Django 4.1.13 on 2024-08-18 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0023_toreview_quotes_file"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="toreview",
            unique_together=set(),
        ),
    ]
