# Generated by Django 6.0.4 on 2026-04-12 15:18

from django.db import migrations, models
from django.db.models import Count


def populate_tag_names(apps, schema_editor):
    Tag = apps.get_model("main", "Tag")
    for tag in Tag.objects.filter(name=""):
        tag.name = tag.name_slug
        tag.save(update_fields=["name"])


def deduplicate_author_slugs(apps, schema_editor):
    """Merge authors that share a name_slug, keeping the one with the lowest id."""
    Author = apps.get_model("main", "Author")
    Book = apps.get_model("main", "Book")

    dupes = Author.objects.values("name_slug").annotate(c=Count("id")).filter(c__gt=1)
    for entry in dupes:
        authors = list(
            Author.objects.filter(name_slug=entry["name_slug"]).order_by("id")
        )
        keep = authors[0]
        for duplicate in authors[1:]:
            Book.objects.filter(primary_author=duplicate).update(primary_author=keep)
            for book in Book.objects.filter(additional_authors=duplicate):
                book.additional_authors.remove(duplicate)
                book.additional_authors.add(keep)
            duplicate.delete()


class Migration(migrations.Migration):
    dependencies = [("main", "0024_alter_book_pages")]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="name",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.RunPython(populate_tag_names, migrations.RunPython.noop),
        migrations.RunPython(deduplicate_author_slugs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="author",
            name="name_slug",
            field=models.CharField(max_length=300, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name="book", unique_together={("primary_author", "title_slug")}
        ),
    ]
