# Generated by Django 6.0.4 on 2026-04-12 16:52

from django.db import migrations


def delete_square_thumbnails(apps, schema_editor):
    Thumbnail = apps.get_model("main", "Thumbnail")
    for thumb in Thumbnail.objects.filter(size="square"):
        if thumb.thumb:
            thumb.thumb.delete(save=False)
        thumb.delete()


class Migration(migrations.Migration):
    dependencies = [("main", "0025_tag_name_alter_author_name_slug_and_more")]

    operations = [
        migrations.RunPython(delete_square_thumbnails, migrations.RunPython.noop)
    ]
