# Generated by Django 6.0.4 on 2026-06-03 07:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("main", "0026_remove_square_thumbnails")]

    operations = [
        migrations.AddField(
            model_name="book",
            name="ui_color",
            field=models.CharField(blank=True, max_length=7, null=True),
        )
    ]
