# Generated by Django 6.0.5 on 2026-07-03 08:01

import datetime as dt

import django.db.models.deletion
from django.db import migrations, models


def backfill_reads(apps, schema_editor):
    Review = apps.get_model("main", "Review")
    Read = apps.get_model("main", "Read")
    reads = []
    for review in Review.objects.only(
        "book_id", "dates_read", "did_not_finish", "latest_date"
    ).iterator():
        dates_read = review.dates_read or review.latest_date.isoformat()
        reads.extend(
            Read(
                book_id=review.book_id,
                finished_on=dt.date.fromisoformat(part.strip()),
                # a DNF book was never finished, so the flag applies to all reads
                did_not_finish=review.did_not_finish,
            )
            for part in dates_read.split(",")
            if part.strip()
        )
    Read.objects.bulk_create(reads)


class Migration(migrations.Migration):
    dependencies = [("main", "0028_recompute_cover_colours")]

    operations = [
        migrations.CreateModel(
            name="Read",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("finished_on", models.DateField()),
                ("started_on", models.DateField(blank=True, null=True)),
                ("did_not_finish", models.BooleanField(default=False)),
                (
                    "format",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("paper", "paper"),
                            ("ebook", "ebook"),
                            ("audio", "audio"),
                        ],
                        max_length=5,
                        null=True,
                    ),
                ),
                ("source", models.CharField(blank=True, max_length=300, null=True)),
                ("total_time_seconds", models.IntegerField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reads",
                        to="main.book",
                    ),
                ),
            ],
            options={"ordering": ("-finished_on",)},
        ),
        migrations.RunPython(backfill_reads, migrations.RunPython.noop),
        migrations.RemoveField(model_name="review", name="dates_read"),
        migrations.RemoveField(model_name="review", name="did_not_finish"),
    ]
