# Generated by Django 6.0.5 on 2026-07-03 12:00

import datetime as dt

import django.db.models.deletion
from django.db import migrations, models

from scriptorium.main.utils import slugify


def copy_series(apps, schema_editor):
    Book = apps.get_model("main", "Book")
    Series = apps.get_model("main", "Series")
    for book in Book.objects.exclude(series_name=None).exclude(series_name=""):
        # Different spellings can slugify to the same series; reuse the row.
        series, _ = Series.objects.get_or_create(
            name_slug=slugify(book.series_name), defaults={"name": book.series_name}
        )
        book.series_id = series.pk
        book.save(update_fields=["series"])


def set_book_statuses(apps, schema_editor):
    Book = apps.get_model("main", "Book")
    Book.objects.filter(review__isnull=False, review__is_draft=False).update(
        status="reviewed"
    )
    Book.objects.filter(review__isnull=False, review__is_draft=True).update(
        status="to_review"
    )


def convert_toreview(apps, schema_editor):
    """Unmatched ToReview entries become to-review books with a Read per date.

    Matched entries point at already-reviewed books and carry no extra data,
    so they are simply dropped with the table. Any uploaded quotes_file stays
    on disk untouched.
    """
    Author = apps.get_model("main", "Author")
    Book = apps.get_model("main", "Book")
    Read = apps.get_model("main", "Read")
    Series = apps.get_model("main", "Series")
    ToReview = apps.get_model("main", "ToReview")
    for to_review in ToReview.objects.filter(book__isnull=True):
        author_slug = slugify(to_review.author)
        title_slug = slugify(to_review.title)
        # Mirror the old runtime ToReview.match(): prefer an exact
        # (author, title) match, but fall back to the title alone, since
        # author spellings often differ between import sources.
        book = (
            Book.objects.filter(
                primary_author__name_slug=author_slug, title_slug=title_slug
            ).first()
            or Book.objects.filter(title_slug=title_slug).first()
        )
        if book:
            if to_review.date:
                # Like the old _match_dates(): a read within a week of the
                # row's date means the row is already accounted for, so it
                # is dropped just as match() + done used to do.
                window = (
                    to_review.date - dt.timedelta(days=7),
                    to_review.date + dt.timedelta(days=7),
                )
                if Read.objects.filter(book=book, finished_on__range=window).exists():
                    continue
            if book.status == "to_read":
                book.status = "to_review"
                book.save(update_fields=["status"])
        else:
            author, _ = Author.objects.get_or_create(
                name_slug=author_slug, defaults={"name": to_review.author}
            )
            series = None
            if to_review.series:
                series, _ = Series.objects.get_or_create(
                    name_slug=slugify(to_review.series),
                    defaults={"name": to_review.series},
                )
            book = Book.objects.create(
                title=to_review.title,
                title_slug=title_slug,
                primary_author=author,
                status="to_review",
                series=series,
                series_position=to_review.series_position,
            )
        if to_review.date:
            Read.objects.create(
                book=book,
                finished_on=to_review.date,
                source="import",
                notes=to_review.notes or None,
            )
        elif to_review.notes and not book.plot:
            # Without a date there is no Read row to carry the notes.
            book.plot = to_review.notes
            book.save(update_fields=["plot"])


def convert_toread(apps, schema_editor):
    Author = apps.get_model("main", "Author")
    Book = apps.get_model("main", "Book")
    ToRead = apps.get_model("main", "ToRead")
    for to_read in ToRead.objects.all():
        author, _ = Author.objects.get_or_create(
            name_slug=slugify(to_read.author), defaults={"name": to_read.author}
        )
        title_slug = slugify(to_read.title)
        if Book.objects.filter(primary_author=author, title_slug=title_slug).exists():
            continue
        Book.objects.create(
            title=to_read.title,
            title_slug=title_slug,
            primary_author=author,
            status="to_read",
            shelf=to_read.shelf,
            pages=to_read.pages,
            source=to_read.source,
        )


class Migration(migrations.Migration):
    dependencies = [("main", "0029_read_backfill_dates_read")]

    operations = [
        migrations.CreateModel(
            name="Series",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=300)),
                ("name_slug", models.CharField(max_length=300, unique=True)),
                ("text", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="book",
            name="status",
            field=models.CharField(
                choices=[
                    ("to_read", "to read"),
                    ("to_review", "to review"),
                    ("reviewed", "reviewed"),
                ],
                default="to_read",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="shelf",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="series_position",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.RenameField(
            model_name="book", old_name="series", new_name="series_name"
        ),
        migrations.AddField(
            model_name="book",
            name="series",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="books",
                to="main.series",
            ),
        ),
        migrations.RunPython(copy_series, migrations.RunPython.noop),
        migrations.RunPython(set_book_statuses, migrations.RunPython.noop),
        migrations.RunPython(convert_toreview, migrations.RunPython.noop),
        migrations.RunPython(convert_toread, migrations.RunPython.noop),
        migrations.RemoveField(model_name="book", name="series_name"),
        migrations.RemoveField(model_name="review", name="is_draft"),
        migrations.DeleteModel(name="ToRead"),
        migrations.DeleteModel(name="ToReview"),
    ]
