# Generated by Django 6.0.5 on 2026-07-03 12:00

from django.db import migrations, models


def copy_reviews(apps, schema_editor):
    Book = apps.get_model("main", "Book")
    Review = apps.get_model("main", "Review")
    for review in Review.objects.all().iterator():
        Book.objects.filter(pk=review.book_id).update(
            text=review.text,
            tldr=review.tldr,
            rating=review.rating,
            feed_date=review.feed_date,
            social=review.social,
        )


class Migration(migrations.Migration):
    dependencies = [("main", "0030_book_status_series_collapse_queues")]

    operations = [
        migrations.AddField(
            model_name="book", name="text", field=models.TextField(null=True)
        ),
        migrations.AddField(
            model_name="book",
            name="tldr",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="book",
            name="rating",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="book", name="feed_date", field=models.DateField(null=True)
        ),
        migrations.AddField(
            model_name="book", name="social", field=models.JSONField(null=True)
        ),
        migrations.RunPython(copy_reviews, migrations.RunPython.noop),
        migrations.DeleteModel(name="Review"),
    ]
