# Generated by Django 6.0.5 on 2026-07-03 11:12

from django.db import migrations, models
from django.db.models.functions import Coalesce


def backfill_review_updated(apps, schema_editor):
    """Existing reviews predate the freshness marker; treat them as current
    as of the best "last touched" date we have: the feed date, falling back
    to the latest read, falling back to the date the book was added."""
    Book = apps.get_model("main", "Book")
    Read = apps.get_model("main", "Read")
    latest_read = (
        Read.objects.filter(book=models.OuterRef("pk"))
        .order_by("-finished_on")
        .values("finished_on")[:1]
    )
    Book.objects.filter(status="reviewed").update(
        review_updated=Coalesce("feed_date", models.Subquery(latest_read), "date_added")
    )


class Migration(migrations.Migration):
    dependencies = [("main", "0031_collapse_review_into_book")]

    operations = [
        migrations.AddField(
            model_name="book", name="review_updated", field=models.DateField(null=True)
        ),
        migrations.RunPython(backfill_review_updated, migrations.RunPython.noop),
    ]
