# Generated by Django 6.0.5 on 2026-07-03 13:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("main", "0033_apitoken")]

    operations = [
        migrations.AddField(
            model_name="read",
            name="highlights",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="read",
            name="koreader_md5",
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
    ]
